
export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";

export const REMOVE_ADDRESS = "REMOVE_ADDRESS";

export const UPDATE_ADDRESS = "UPDATE_ADDRESS";

export const EMAIL_UPDATE_OTP_REQUEST = "EMAIL_UPDATE_OTP_REQUEST";
export const EMAIL_UPDATE_OTP_SUCCESS = "EMAIL_UPDATE_OTP_SUCCESS";
export const EMAIL_UPDATE_OTP_FAILURE = "EMAIL_UPDATE_OTP_FAILURE";

export const MOBILE_UPDATE_OTP_REQUEST = "MOBILE_UPDATE_OTP_REQUEST";
export const MOBILE_UPDATE_OTP_SUCCESS = "MOBILE_UPDATE_OTP_SUCCESS";
export const MOBILE_UPDATE_OTP_FAILURE = "MOBILE_UPDATE_OTP_FAILURE";